name: Build vizzytrace
on:
  push:
    branches: [ '**' ]
    tags-ignore: [ '*' ]
  pull_request:
    branches: [ '**' ]
    tags-ignore: [ '*' ]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Install Scons
        run: |
          sudo apt-get install -y scons

      - name: Build
        run: scons
